### ISSUE TITLE
Mobile browsers hides options for multi selects

### ISSUE THREAD

**Issue by privatemonkey** [statisticssweden/pxweb-scb-style#38]
Chrome/Safari shows only a field one line tall.
Text is either option value (if only one selected) or "x selected".
On click will show system dialog for multi select.

Firefox shows all options.
On click will show system dialog for multi select

> Since we already show number of selected options, the mobile experience is that this is shown twice.

## Todo

- [x] Make sure padding is only implemented in "Select variable" select boxes
- [ ] Replace select box options with spans in prototype. Hide options but make select box clickable
- [x] Do iPads and other tablets use system dialog for multi select?
